<a href="https://colab.research.google.com/github/AbhijeetBeedikar/Handwritten-Digit_Reader/blob/main/Handwritten_Digit_Reader.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install bigdl


  Using cached protobuf-3.19.5-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (787 bytes)
Using cached protobuf-3.19.5-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.1 MB)
  Attempting uninstall: protobuf
    Found existing installation: protobuf 3.20.1
    Uninstalling protobuf-3.20.1:
      Successfully uninstalled protobuf-3.20.1
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-ai-generativelanguage 0.6.10 requires protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<6.0.0dev,>=3.20.2, but you have protobuf 3.19.5 which is incompatible.
google-cloud-aiplatform 1.74.0 requires protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<6.0.0dev,>=3.20.2, but you have protobuf 3.19.5 which is incompatible.
google-cloud-bigquery-connection 1.17.0 requires protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4

In [ ]:
!pip install protobuf==3.20.1
!pip install keras==2.10.0 # Force install a specific version of Keras that's compatible with bigdl.nano
!pip install tensorflow==2.10.0

  Using cached protobuf-3.20.1-cp310-cp310-manylinux_2_12_x86_64.manylinux2010_x86_64.whl.metadata (698 bytes)
Using cached protobuf-3.20.1-cp310-cp310-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (1.1 MB)
  Attempting uninstall: protobuf
    Found existing installation: protobuf 3.19.6
    Uninstalling protobuf-3.19.6:
      Successfully uninstalled protobuf-3.19.6
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
bigdl-nano 2.4.0 requires protobuf==3.19.5, but you have protobuf 3.20.1 which is incompatible.
google-ai-generativelanguage 0.6.10 requires protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<6.0.0dev,>=3.20.2, but you have protobuf 3.20.1 which is incompatible.
google-api-core 2.19.2 requires protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<6.0.0.dev0,>=3.19.5, but you have protobuf 3.20.1 which is incompa

  Using cached protobuf-3.19.6-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (787 bytes)
Using cached protobuf-3.19.6-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.1 MB)
  Attempting uninstall: protobuf
    Found existing installation: protobuf 3.20.1
    Uninstalling protobuf-3.20.1:
      Successfully uninstalled protobuf-3.20.1
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
bigdl-nano 2.4.0 requires protobuf==3.19.5, but you have protobuf 3.19.6 which is incompatible.
google-ai-generativelanguage 0.6.10 requires protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<6.0.0dev,>=3.20.2, but you have protobuf 3.19.6 which is incompatible.
google-cloud-aiplatform 1.74.0 requires protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<6.0.0dev,>=3.20.2, but you have protobuf 3.19.6 which is incompatible.
googl

In [16]:
from bigdl.nano.tf.keras import Sequential
from tensorflow.keras.layers import Dense
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from tensorflow.keras.utils import to_categorical
from sklearn.preprocessing import StandardScaler
import pandas as pd
import numpy as np

standard = StandardScaler()
#!pip install tensorflow
from tensorflow.keras.datasets import mnist
a = mnist.load_data(path="mnist.npz")

x_train,x_test,y_train,y_test = train_test_split(a[0][0],to_categorical(pd.Series(a[0][1])),test_size = 0.25, random_state=0)
rand = []
for i in range(len(x_train)):
  rand.append(standard.fit_transform(x_train[i]))
x_train = np.array(rand)
x_train = x_train.reshape(-1, 784)
rand = []
for i in range(len(x_test)):
  rand.append(standard.fit_transform(x_test[i]))
x_test = np.array(rand)
x_test = x_test.reshape(-1, 784)

In [17]:
print(x_train[0])

[ 0.          0.          0.          0.          0.         -0.38988724
 -0.38305146 -0.34728985 -0.39753564 -0.59744039 -0.63813202 -0.69903
 -0.68768994 -0.76461859 -0.81077526 -0.82797778 -0.98295804 -1.01774541
 -0.85887377 -0.53062051 -0.37964354  0.          0.          0.
  0.          0.          0.          0.          0.          0.
  0.          0.          0.         -0.38988724 -0.38305146 -0.34728985
 -0.39753564 -0.59744039 -0.63813202 -0.69903    -0.68768994 -0.76461859
 -0.81077526 -0.82797778 -0.98295804 -1.01774541 -0.85887377 -0.53062051
 -0.37964354  0.          0.          0.          0.          0.
  0.          0.          0.          0.          0.          0.
  0.         -0.38988724 -0.38305146 -0.34728985 -0.39753564 -0.59744039
 -0.63813202 -0.69903    -0.68768994 -0.76461859 -0.81077526 -0.82797778
 -0.98295804 -1.01774541 -0.85887377 -0.53062051 -0.37964354  0.
  0.          0.          0.          0.          0.          0.
  0.          0.          0. 

In [ ]:
print(to_categorical(pd.Series(a[0][1])))
a[0][1]

[[0. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]]


array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [18]:
# Initialise the neural network as model
model = Sequential()

# Add the first hidden layer with 6 nodes. Input_dim refers to the number of columns/number of features in x_values or the input layer.
# Activation refers to how the nodes/neurons are activated. We will use relu. Other common activations are 'sigmoid' and 'tanh'
model.add(Dense(784,input_dim=784,activation='relu'))

# Add the hidden layer with 6 nodes.
model.add(Dense(16,activation='relu'))
model.add(Dense(16,activation='relu'))

# Add the output layer with 3 nodes. The activation used has to be 'softmax'. Softmax is used when you are dealing with categorical outputs or targets.
model.add(Dense(10,activation='sigmoid'))

# Compile the model together. The optimizer refers to the method to make the adjustment within the model. Loss refers to how the difference between the predicted out
model.compile(optimizer='adam',loss='categorical_crossentropy',metrics=['accuracy'])
model.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_9 (Dense)             (None, 784)               615440    
                                                                 
 dense_10 (Dense)            (None, 16)                12560     
                                                                 
 dense_11 (Dense)            (None, 16)                272       
                                                                 
 dense_12 (Dense)            (None, 10)                170       
                                                                 
Total params: 628,442
Trainable params: 628,442
Non-trainable params: 0
_________________________________________________________________


In [19]:
model.fit(x_train,y_train,epochs=20,shuffle=True,validation_data=(x_test,y_test), batch_size=1)

Epoch 1/20
45000/45000 [==============================] - 156s 3ms/step - loss: 0.3221 - accuracy: 0.9141 - val_loss: 0.1757 - val_accuracy: 0.9557
Epoch 2/20
45000/45000 [==============================] - 154s 3ms/step - loss: 0.1835 - accuracy: 0.9568 - val_loss: 0.1697 - val_accuracy: 0.9589
Epoch 3/20
45000/45000 [==============================] - 150s 3ms/step - loss: 0.1534 - accuracy: 0.9644 - val_loss: 0.2367 - val_accuracy: 0.9507
Epoch 4/20
45000/45000 [==============================] - 155s 3ms/step - loss: 0.1350 - accuracy: 0.9705 - val_loss: 0.1932 - val_accuracy: 0.9600
Epoch 5/20
45000/45000 [==============================] - 150s 3ms/step - loss: 0.1337 - accuracy: 0.9717 - val_loss: 0.2711 - val_accuracy: 0.9580
Epoch 6/20
45000/45000 [==============================] - 152s 3ms/step - loss: 0.1273 - accuracy: 0.9754 - val_loss: 0.2291 - val_accuracy: 0.9630
Epoch 7/20
45000/45000 [==============================] - 151s 3ms/step - loss: 0.1224 - accuracy: 0.9763 - val_